# Generated by Django 4.2 on 2023-06-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_audio_audio_link_audio_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosegments',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
